apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    name: demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/v1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce